# Generated by Django 6.0.3 on 2026-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('is_open_to_all', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('participation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('status', models.CharField(default='upcoming', max_length=20)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
