# Generated by Django 6.0.3 on 2026-03-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('booking_allowed', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('advance_booking_days', models.IntegerField(default=7)),
                ('max_booking_hours', models.IntegerField(default=4)),
                ('booking_slot_duration', models.IntegerField(default=60)),
                ('is_chargeable', models.BooleanField(default=False)),
                ('charges_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('refundable_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cleaning_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_bookings_per_flat_per_month', models.IntegerField(default=2)),
                ('operational_hours', models.JSONField(default=dict)),
                ('blackout_dates', models.JSONField(default=list)),
                ('rules_and_regulations', models.TextField(blank=True)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('manager_contact', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmenityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('purpose', models.CharField(max_length=200)),
                ('expected_guests', models.IntegerField(default=0)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('damage_reported', models.BooleanField(default=False)),
                ('damage_details', models.TextField(blank=True)),
                ('damage_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='amenities.amenity')),
            ],
        ),
    ]
