# Generated by Django 6.0.3 on 2026-03-11 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitybooking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amenitybooking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amenitybooking',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.flat'),
        ),
    ]
