# Generated by Django 6.0.3 on 2026-03-11 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('visitor_type', models.CharField(choices=[('guest', 'Guest'), ('delivery', 'Delivery'), ('service', 'Service'), ('vendor', 'Vendor')], max_length=20)),
                ('id_proof_type', models.CharField(blank=True, max_length=30)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/')),
                ('visiting_person', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('none', 'None')], default='none', max_length=10)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('entry_gate', models.CharField(blank=True, max_length=50)),
                ('exit_gate', models.CharField(blank=True, max_length=50)),
                ('is_pre_approved', models.BooleanField(default=False)),
                ('pre_approval_date', models.DateTimeField(blank=True, null=True)),
                ('expected_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('denied', 'Denied')], default='expected', max_length=20)),
                ('denial_reason', models.TextField(blank=True)),
                ('is_frequent_visitor', models.BooleanField(default=False)),
                ('visitor_pass_id', models.CharField(blank=True, max_length=50)),
                ('pass_validity', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_visitors', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_visitors', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='flats.flat')),
                ('pre_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_approved_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['flat', 'check_in_time'], name='visitors_vi_flat_id_137c0d_idx'), models.Index(fields=['status', 'check_in_time'], name='visitors_vi_status_70b957_idx'), models.Index(fields=['contact_no'], name='visitors_vi_contact_740e37_idx')],
            },
        ),
    ]
