# Generated by Django 6.0.3 on 2026-03-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('billing_period', models.DateField()),
                ('base_maintenance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('electricity_common_area', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sinking_fund', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('repair_fund', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('parking_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amenity_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('previous_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('net_banking', 'Net Banking')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('due_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_bills', to='flats.flat')),
            ],
            options={
                'indexes': [models.Index(fields=['flat', 'billing_period'], name='maintenance_flat_id_56034b_idx'), models.Index(fields=['status', 'due_date'], name='maintenance_status_4e2b2a_idx'), models.Index(fields=['month', 'year'], name='maintenance_month_b40b13_idx')],
            },
        ),
    ]
