# Generated by Django 6.0.3 on 2026-03-11 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_flats',
            field=models.ManyToManyField(blank=True, to='flats.flat'),
        ),
        migrations.AddField(
            model_name='noticeacknowledgment',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.notice'),
        ),
        migrations.AddField(
            model_name='noticeacknowledgment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='acknowledged_by',
            field=models.ManyToManyField(related_name='acknowledged_notices', through='notices.NoticeAcknowledgment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticeattachment',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notices.notice'),
        ),
    ]
