# Generated by Django 6.0.3 on 2026-03-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20, unique=True)),
                ('slot_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('zone', models.CharField(blank=True, max_length=10)),
                ('allocation_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('visitor', 'Visitor')], max_length=20)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=10)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_make_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('rc_book_photo', models.ImageField(blank=True, null=True, upload_to='rc_books/')),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('monthly_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('parking_sticker_number', models.CharField(blank=True, max_length=30)),
                ('sticker_issued_date', models.DateField(blank=True, null=True)),
                ('temporary_allocation_start', models.DateField(blank=True, null=True)),
                ('temporary_allocation_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_to_flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flats.flat')),
            ],
        ),
    ]
