# Generated by Django 6.0.3 on 2026-03-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('alternate_contact', models.CharField(blank=True, max_length=15)),
                ('floor_no', models.IntegerField()),
                ('tower_block', models.CharField(max_length=10)),
                ('bhk_type', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('Penthouse', 'Penthouse')], max_length=20)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=8)),
                ('occupancy_status', models.CharField(choices=[('owner_occupied', 'Owner Occupied'), ('rented', 'Rented'), ('vacant', 'Vacant')], default='owner_occupied', max_length=20)),
                ('tenant_name', models.CharField(blank=True, max_length=100)),
                ('tenant_contact', models.CharField(blank=True, max_length=15)),
                ('tenant_email', models.EmailField(blank=True, max_length=254)),
                ('lease_start_date', models.DateField(blank=True, null=True)),
                ('lease_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tower_block', 'floor_no'], name='flats_flat_tower_b_e0386d_idx'), models.Index(fields=['occupancy_status'], name='flats_flat_occupan_606a09_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('other', 'Other')], max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='family/')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='flats.flat')),
            ],
        ),
        migrations.CreateModel(
            name='DomesticHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('maid', 'Maid'), ('cook', 'Cook'), ('driver', 'Driver'), ('other', 'Other')], max_length=20)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='domestic/')),
                ('working_hours', models.CharField(blank=True, max_length=50)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_help', to='flats.flat')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_allocations', to='flats.flat')),
            ],
        ),
    ]
