# Generated by Django 6.0.3 on 2026-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=30)),
                ('paid_to', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_attachment', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('requires_approval', models.BooleanField(default=True)),
                ('approval_status', models.CharField(default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_budgeted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
