# Generated by Django 6.0.3 on 2026-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.IntegerField()),
                ('access_level', models.CharField(default='all', max_length=20)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('has_expiry', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
