# Generated by Django 6.0.3 on 2026-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(max_length=30)),
                ('is_24x7_available', models.BooleanField(default=False)),
                ('available_hours', models.CharField(blank=True, max_length=50)),
                ('priority_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
